### ISSUE TITLE
Testing with SentryPeer

### ISSUE THREAD

**Issue by ghenry** [Pepelux/sippts#26]
Hi @Pepelux 

I saw your project in [the news](https://www.rtcsec.com/newsletter/2022-10-rtcsec-news/#new-sippts-released) and thought I should have a play with it against [SentryPeer](https://github.com/SentryPeer/SentryPeer).

Any tips for where to start?

Thanks,
Gavin.

**Comment by Pepelux** [comment]
Hi Gavin 

I saw your project and it is very interesting. SIPPTS is a suite of tools for pentesting and I don't know how you can use it with SentryPeer because it checks numbers. Maybe you can try with sipinvite.py to send INVITE messages with different From and To headers. Or maybe sipsend.py to create custom messages.

Cheers

**Comment by ghenry** [comment]
Hi @Pepelux 

Sorry, I missed your reply and only saw the closed notification from GitHub.

Thanks, I'll have a play with that first then. Much appreciated for the reply!

Gavin.

**Comment by Pepelux** [comment]
Thanks Gavin. If you have any question you can send me an email

Cheers
